bak4bio-server/config/routes.rb
Bak4bioServer::Application.routes.draw do
  resources :blasts

  devise_for :users

  resources :contents do
    member do
      get :download
    end
  end
  
  resources :tokens, :only => [:create, :destroy] do
    member do
      get 'check'
    end
  end

  root :to => 'contents#index'

end

bak4bio-server/app/models/content.rb
class Content < ActiveRecord::Base
  has_many :blasts, :foreign_key => :entry_id
  belongs_to :owner, :class_name => "User", :foreign_key => :owner_id
  
  paginates_per 10
  
  attr_accessible :source, :source_file_name, :source_content_type, 
                  :source_file_size, :source_updated_at,
                  :description, :owner_id
                  
  has_attached_file :source,
                    :url => "/:current_user/:basename.:extension",
                    :path => "#{Rails.root}/public:url" 
                    
                    
  validates_presence_of :description, :owner_id, :source                  
  validates_uniqueness_of :source_file_name, :if => :has_source 
  validates_uniqueness_of :description
  
  before_destroy :can_remove?
  
  private
  def has_source
    !self.source.blank?
  end
  
  def can_remove?
    unless self.blasts.blank?
      errors.add(:base, "Can't remove content with blast operations")
      return false
    end
  end
                                        
  # interpolate in paperclip
  Paperclip.interpolates :current_user  do |attachment, style|
    attachment.instance.owner_id
  end
 
end

bak4bio-server/app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  load_resource
  authorize_resource
  
  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.accessible_by(current_ability).page params[:page]
    
    if params[:filter]
      @contents = @contents.where("description LIKE ?", "%#{params[:filter]}%")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end

  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new
    @content.owner_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_path, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to contents_path, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.destroy
         format.html { redirect_to contents_url, notice: 'Content was successfully removed.' }
         format.json { head :no_content }
      else  
        format.html { redirect_to contents_url, alert: @content.errors.full_messages }
        format.json { render json: @content.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /contents/1/download
  def download
    @content = Content.find(params[:id])
    
    send_file @content.source.path, :type => @content.source_content_type, :filename => @content.source_file_name
    
  end
end

bak4bio-server/app/helpers/contents_helper.rb
module ContentsHelper
end

bak4bio-server/app/views/contents/_form.html.erb
  <%= f.hidden_field :owner_id %>

<div class="group">
  <%= f.label :description, t("activerecord.attributes.content.description"), :class => :label %>
  <%= f.text_field :description, :class => 'text_field' %>
  <span class="description">Ex: a simple text</span>  
</div>

<div class="group">
  <%= f.label :source, t("activerecord.attributes.content.source", :default => "Source"), :class => :label %>
  <%= f.file_field :source, :class => 'text_field' %>
</div>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), contents_path, :class => "text_button_padding link_button" %>
</div>

bak4bio-server/app/views/contents/_sidebar.html.erb
<!--
  
  <div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

-->

bak4bio-server/app/views/contents/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_content_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Content</h2>
    <div class="inner">
      <%= form_for @content, :url => content_path(@content), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

bak4bio-server/app/views/contents/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Contents</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th>
            <%= t("activerecord.attributes.content.description") %>
          </th>
          <th>
            <%= t("activerecord.attributes.content.source") %>
          </th>
          <th>
            <%= t("web-app-theme.created_at", :default => "Created at")  %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @contents.each do |content| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= content.description %>
          </td>
                    <td>
            <%= link_to content.source_file_name, edit_content_path(content) %>
          </td>
                    <td>
            <%= content.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.edit", :default => "Download")}", download_content_path(content) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_content_path(content) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", content_path(content), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @contents %>
        <%= page_entries_info @contents %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

bak4bio-server/app/views/contents/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", contents_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_content_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Content</h2>
    <div class="inner">
      <%= form_for :content, :url => contents_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>