bak4bio-server/config/routes.rb
Bak4bioServer::Application.routes.draw do
  resources :blasts

  devise_for :users

  resources :contents do
    member do
      get :download
    end
  end
  
  resources :tokens, :only => [:create, :destroy] do
    member do
      get 'check'
    end
  end

  root :to => 'contents#index'

end

bak4bio-server/app/models/blast.rb
class Blast < ActiveRecord::Base
  belongs_to :owner, :class_name => "User", :foreign_key => :owner_id
  belongs_to :entry, :class_name => "Content", :foreign_key => :entry_id
  belongs_to :output, :class_name => "Content", :foreign_key => :output_id
  
  attr_accessible :entry_id, :database, :end_at, :expect, :gap_costs, :m_scores, 
                  :max_matches_range, :max_target_sequence, :output_id,
                  :owner_id, :program, :status, :start_at, :title, :word_size
                  
  validates_presence_of :title, :owner_id, :entry_id
  validates_uniqueness_of :title, :scope => :owner_id    
  
  
  #can_remove?            
                  
end

bak4bio-server/app/controllers/blasts_controller.rb
class BlastsController < ApplicationController
  load_resource
  authorize_resource
  before_filter :load_contents, :except => [:index]
  
  # GET /blasts
  # GET /blasts.json
  def index
    @blasts = Blast.accessible_by(current_ability)
    
    if params[:filter] && !params[:filter].blank?
      @blasts = Blast.where("title LIKE ?", "%#{params[:filter]}%")
    end
    
    if params[:status] && !params[:status].blank?
      @blasts = Blast.where(:status => params[:status])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blasts.to_json(:include => [:output, :owner, :entry])}
    end
  end

  # GET /blasts/1
  # GET /blasts/1.json
  def show
    @blast = Blast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blast }
    end
  end

  # GET /blasts/new
  # GET /blasts/new.json
  def new
    @blast = Blast.new
    @blast.owner_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blast.to_json(:include => :output) }
    end
  end

  # GET /blasts/1/edit
  def edit
    @blast = Blast.find(params[:id])
  end

  # POST /blasts
  # POST /blasts.json
  def create
    @blast = Blast.new(params[:blast])
    @blast.start_at = Time.now
    @blast.owner_id = current_user.id
    @blast.status = "pending"

    respond_to do |format|
      if @blast.save
        format.html { redirect_to blasts_path, notice: 'Blast was successfully created.' }
        format.json { render json: @blast, status: :created, location: @blast }
      else
        format.html { render action: "new" }
        format.json { render json: @blast.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blasts/1
  # PUT /blasts/1.json
  def update
    @blast = Blast.find(params[:id])

    respond_to do |format|
      if @blast.update_attributes(params[:blast])
        format.html { redirect_to blasts_path, notice: 'Blast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blast.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blasts/1
  # DELETE /blasts/1.json
  def destroy
    @blast = Blast.find(params[:id])
    @blast.destroy

    respond_to do |format|
      format.html { redirect_to blasts_url }
      format.json { head :no_content }
    end
  end
  
  private
  def load_contents
    @contents = Content.accessible_by(current_ability)
  end
  
end

bak4bio-server/app/helpers/blasts_helper.rb
module BlastsHelper
end

bak4bio-server/app/views/blasts/_form.html.erb
  <%= f.hidden_field :owner_id %>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.blast.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: Job Title</span>
  </div>

  <div class="group">
    <%= f.label :entry_id, t("activerecord.attributes.blast.entry_id", :default => "Entry"), :class => :label %>
    
    <%= f.select("entry_id", 
                @contents.collect { |p| ["#{p.description} - #{p.source_file_name}", p.id]},
                {}, 
                :style => "width:250px;" ) %>
  </div>

  <% if f.object && f.object.output %>
  <div class="group">
    <%= f.label :output_id, t("activerecord.attributes.blast.output_id", :default => "Output (Result)"), :class => :label %>
    <%= link_to f.object.output.description, f.object.output.source.url %>
  </div>
  <% end %>

  <div class="group">
    <%= f.label :program, t("activerecord.attributes.blast.program", :default => "Program"), :class => :label %>
    <%= f.select(:program, {"blastn" => "blastn", "blastp" => "blastp", "tblastn" => "tblastn", "blastx" => "blastx", "tbalstn" => "tbalstn"}, {}, :style => "width:250px;")  %>
  </div>

  <div class="group">
    <%= f.label :database, t("activerecord.attributes.blast.database", :default => "Database"), :class => :label %>
    <%= f.select(:database, {"nr" => "nr", "refseq_rna" => "refseq_rna", "refseq_genomic" => "refseq_genomic", "chromosome" => "chromosome", "est" => "est", "gss" => "gss", 
                            "htgs" => "htgs", "pdb" => "pdb", "alu" => "alu", "dbsts" => "dbsts", "tsa_nt" => "tsa_nt", "alu" => "alu"}, {}, :style => "width:250px;")  %>
  </div>

  <div class="group">
    <%= f.label :word_size, t("activerecord.attributes.blast.word_size", :default => "Word size"), :class => :label %>
    <%= f.select(:word_size, {"11" => "11", "7" => "7", "15" => "15"}, {}, :style => "width:250px;")  %>
  </div>

  <div class="group">
    <%= f.label :max_target_sequence, t("activerecord.attributes.blast.max_target_sequence", :default => "Max target sequence"), :class => :label %>
    <%= f.select(:max_target_sequence, {"10" => "10", "50" => "50", "100" => "100", "250" => "250",
                                        "500" => "500", "1000" => "1000", "5000" => "5000",
                                        "10000" => "10000", "20000" => "20000"}, {}, :style => "width:250px;")  %>
  </div>

  <div class="group">
    <%= f.label :expect, t("activerecord.attributes.blast.expect", :default => "Expect"), :class => :label %>
    <%= f.text_field :expect, :class => 'text_field' %>
    <span class="description">Ex: 10</span>
  </div>

  <div class="group">
    <%= f.label :max_matches_range, t("activerecord.attributes.blast.max_matches_range", :default => "Max matches range"), :class => :label %>
    <%= f.text_field :max_matches_range, :class => 'text_field' %>
    <span class="description">Ex: 0</span>
  </div>

  <div class="group">
    <%= f.label :m_scores, t("activerecord.attributes.blast.m_scores", :default => "Match/Mismatch scores"), :class => :label %>
    <%= f.select(:m_scores, {"1,-2" => "1,-2", "1,-3" => "1,-3", "1,-4" => "1,-4", "2,-3" => "2,-3", "4,-5" => "4,-5", "1,-1" => "1,-1"}, {}, :style => "width:250px;")  %>
  </div>

  <div class="group">
    <%= f.label :gap_costs, t("activerecord.attributes.blast.gap_costs", :default => "Gap costs"), :class => :label %>
    <%= f.select(:gap_costs, {"5 2" => "5 2", "2 2" => "2 2", "1 2" => "1 2", "1 2" => "0 2", "0 2" => "3 1", "3 1" => "2 1", "2 1" => "1 2", "1 1" => "1 1"}, {}, :style => "width:250px;")  %>
  </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), blasts_path, :class => "text_button_padding link_button" %>
</div>

bak4bio-server/app/views/blasts/_sidebar.html.erb
<!--
  
  <div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

-->

bak4bio-server/app/views/blasts/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", blasts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_blast_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blast_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Blast</h2>
    <div class="inner">
      <%= form_for @blast, :url => blast_path(@blast), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

bak4bio-server/app/views/blasts/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", blasts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_blast_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Blasts</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.blast.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
          <th>
            <%= t("web-app-theme.status", :default => "Status")  %>
          </th>
          <th>
            <%= t("web-app-theme.created_at", :default => "Created at")  %>
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @blasts.each do |blast| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= blast.id %>
          </td>
          <td>
            <%= link_to blast.title, edit_blast_path(blast) %>
          </td>
          <td>
            <%= link_to blast.status, edit_blast_path(blast) %>
          </td>
          <td>
            <%= blast.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_blast_path(blast) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", blast_path(blast), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

bak4bio-server/app/views/blasts/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", blasts_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_blast_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Blast</h2>
    <div class="inner">
      <%= form_for :blast, :url => blasts_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

bak4bio-server/app/views/blasts/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", blasts_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_blast_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", blast_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.blast.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @blast.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.entry_id", :default => t("activerecord.labels.entry_id", :default => "Entry")) %>:</b>
          <%= @blast.entry_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.status", :default => t("activerecord.labels.status", :default => "Status")) %>:</b>
          <%= @blast.status %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.output_id", :default => t("activerecord.labels.output_id", :default => "Output")) %>:</b>
          <%= @blast.output_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.program", :default => t("activerecord.labels.program", :default => "Program")) %>:</b>
          <%= @blast.program %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.database", :default => t("activerecord.labels.database", :default => "Database")) %>:</b>
          <%= @blast.database %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.word_size", :default => t("activerecord.labels.word_size", :default => "Word size")) %>:</b>
          <%= @blast.word_size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.max_target_sequence", :default => t("activerecord.labels.max_target_sequence", :default => "Max target sequence")) %>:</b>
          <%= @blast.max_target_sequence %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.expect", :default => t("activerecord.labels.expect", :default => "Expect")) %>:</b>
          <%= @blast.expect %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.max_matches_range", :default => t("activerecord.labels.max_matches_range", :default => "Max matches range")) %>:</b>
          <%= @blast.max_matches_range %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.m_scores", :default => t("activerecord.labels.m_scores", :default => "M scores")) %>:</b>
          <%= @blast.m_scores %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.blast.gap_costs", :default => t("activerecord.labels.gap_costs", :default => "Gap costs")) %>:</b>
          <%= @blast.gap_costs %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_blast_path(@blast), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), blast_path(@blast), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>